### ISSUE TITLE
Add support for Relive activities

### ISSUE THREAD

**Issue by joaopalmeiro** [spences10/sveltekit-embed#427]
Hi! 👋 

**Is your feature request related to a problem? Please describe.**
I'd like to create a little blog to share some thoughts on 10K runs I've done. In the associated posts, in addition to text, I would like to embed the cool map produced by Relive ([example](https://www.relive.cc/view/vAOZokmYVo6) and [widget example](https://www.relive.cc/view/vAOZokmYVo6/widget)). Since `sveltekit-embed` provides several providers, some of which might also be useful, in such an organized way, I thought I'd consider this package as a dependency and try to contribute a new component to Relive.

**Describe the solution you'd like**
On each activity's page ([example](https://www.relive.cc/view/vAOZokmYVo6)), we can get the code to embed the activity's widget somewhere. Since the provided snippets use [Embedly](https://embed.ly/), but each activity has a widget ready to be used in an `<iframe>`, my proposal would be to adapt the existing `<iframe>` snippet, whose `src` would be just the URL for the widget of an activity (`https://www.relive.cc/view/<ID>/widget`), in a more simplified way.

**Describe alternatives you've considered**
The alternative is to more strictly follow one of the snippets provided via [Embedly](https://embed.ly/), available on each activity's page.

**Additional context**
- [Documentation](https://support.relive.cc/kb/guide/en/how-to-embed-a-relive-video-to-your-webpage-0eb6sNg7g6/Steps/31724)

Let me know your feedback and if I can help with the implementation of this component if it makes sense! 😄

**Comment by spences10** [comment]
Hey @joaopalmeiro!

Yeah, go for it!

Let me know if there's anything that doesn't make sense when you're implementing it
