### ISSUE TITLE
add TickTok widget

### ISSUE THREAD

**Issue by nosovk** [spences10/sveltekit-embed#727]
https://developers.tiktok.com/doc/embed-videos/
it would be nice to add support of ticktok

**Comment by spences10** [comment]
Sure! Get it in there 😊

I think there's one in MDX Embed already (what this package is based off of) if you need an idea of the implementation

Otherwise I'll add it when I get round to working on it again 😅

**Comment by spences10** [comment]
closed with 8c9361fa04907c1f8f1a2c3e46d19f0cb6ebadb3
